addons:
  apt:
    packages:
      - doxygen


jobs:
  include:
  - stage: tests
    name: C Compiling
    language: C
    install:
    - make install_deps
    script:
    - make clean
    - make compile

  - stage: tests
    name: C unittest
    script:
    - make
    - cd bin
    - "./test"
    after_success:
    - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - "./send.sh success $WEBHOOK_URL"
    after_failure:
    - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - "./send.sh failure $WEBHOOK_URL"

  - stage: deploy
    name: deploy to github pages
    script: skip
    before_deploy: doxygen doxygen.txt
    deploy: &pages
      keep_history: true
      provider: pages
      skip_cleanup: true          
      github_token: $GITHUB_TOKEN
      local_dir: docs   

