jobs:
  include:
    - stage: tests
      name: C Compiling
      language: C 
      install: 
        - make install_deps
      script:
        - make clean
        - make compile
    - stage: tests
      name: C unittest
      script:
         - make
         - cd bin
         - ./test
