name: C Unittests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make
    - name: run tests
      run: bin/test
      if: failure()
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

      



      
