name: C Unittests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
          
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make
    - name: run tests
      run: bin/test
