name: C Unittests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make
    - name: run tests
      run: bin/test

      



      
